pipeline {
    agent {
        docker {
            image 'node:18.18.0-alpine3.18'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pnpm install'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/deliver.sh'
                sh './jenkins/scripts/kill.sh'
            }
    }
    }
}