pipeline {
    agent {
        docker {
            image 'node:18.18.0-alpine3.18'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pnpm install'
            }
        }
    }
    stage {
        steps {
            sh './jenkins/deliver.sh'
            input messaje: 'Finished using the web site? (Click Proceed)'
            sh './jenkins/scripts/kill.sh'
        }
    }
}